version: '3'

  #networks:
  #  internal-network:
  #    internal: true

services:

  mysqldb:
    container_name: mysql_notes
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: notesdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password@123
    ports:
      - "3306:3306"
    volumes:
      - ./my-mysql.cnf:/etc/mysql/conf.d/my-mysql.cnf
      # important dont remove below line
      - ./mysql-data:/var/lib/mysql #if we dont have persistent volume or local folder mapping then when we say docker compose down data is gone forever
      - ./dumps/2026_02_28_1772273583/2026_02_28_1772273583.sql:/docker-entrypoint-initdb.d/init.sql

#  portainer:
#    container_name: portainer_notes
#    image: portainer/portainer-ce:sts
#    command: -H unix:///var/run/docker.sock
#    restart: always
#    ports:
#      - 9000:9000
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data

volumes:
  portainer_data:
